// <auto-generated />
using APIproject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIproject.Migrations
{
    [DbContext(typeof(APIprojectContext))]
    partial class APIprojectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIproject.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Franz Kafka",
                            Title = "The Metamorphosis",
                            YearPublished = 1960
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            Title = "1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            Id = 3,
                            Author = "Fyodor Dostoevsky",
                            Title = "The Brothers Karamazov",
                            YearPublished = 1880
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jean-Paul Sartre",
                            Title = "Being and Nothingness",
                            YearPublished = 1943
                        },
                        new
                        {
                            Id = 5,
                            Author = "Franz Kafka",
                            Title = "The Trial",
                            YearPublished = 1925
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
